[project]
name = "iuri-python-release"
dynamic = ["version"]
readme = "README.md"

[tool.setuptools_scm]
local_scheme = "no-local-version"

[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
]
